# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ed0e138019cc0f0251d05752e96475a2"
name = "inventory-seesvee"
application_url = "https://durable-confirm-lewis-improvement.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "abhi-retake.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,write_products"

[auth]
redirect_urls = [
  "https://durable-confirm-lewis-improvement.trycloudflare.com/auth/callback",
  "https://durable-confirm-lewis-improvement.trycloudflare.com/auth/shopify/callback",
  "https://durable-confirm-lewis-improvement.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
